### ISSUE TITLE
proto-build: generated `cosmos.staking.v1beta1.rs` contains clashing `Validators` structs

### ISSUE THREAD

**Issue by tony-iqlusion** [cosmos/cosmos-rust#154]
This is a tracking issue for a breakage in automated codegen.

Currently the generated code contains two different types named `Validators`:

```
$ cargo test
   Compiling cosmos-sdk-proto v0.8.0
error[E0428]: the name `Validators` is defined multiple times
    --> cosmos-sdk-proto/src/prost/cosmos.staking.v1beta1.rs:1115:5
     |
1109 |     pub struct Validators {
     |     --------------------- previous definition of the type `Validators` here
...
1115 |     pub enum Validators {
     |     ^^^^^^^^^^^^^^^^^^^ `Validators` redefined here
     |
     = note: `Validators` must be defined only once in the type namespace of this module
```

The interim solution is to hand-edit the generated code to be:

- `pub struct StakeAuthorizationValidators`
- `pub enum IsStakeAuthorizationValidators`

Ideally this would get resolved in the upstream cosmos-sdk protos so the names don't clash in the generated code.

If that isn't going to happen, we might need to look into something like auto-applying a patch to the generated code to handle renaming the files.

**Comment by tony-iqlusion** [comment]
@jkilpatr @ChristianBorst are you aware of an upstream tracking issue in cosmos-sdk about the clashing names in the protos?

**Comment by rnbguy** [comment]
There is also a related case - [`cosmos.base.abci.v1beta1.Result`](https://github.com/cosmos/cosmos-sdk/blob/fe9a4861d3bf45f52a830f3c02c0ab2ac832f2bc/proto/cosmos/base/abci/v1beta1/abci.proto#L89). It conflicts with [`std::result::Result`](https://doc.rust-lang.org/stable/std/result/enum.Result.html).

**Comment by tony-iqlusion** [comment]
@rnbguy that one's probably fine because it's in its own namespace, whereas the `Validators` struct/enum are in the same namespace and therefore the generated code doesn't compile

**Comment by siulee2** [comment]
same issue

**Comment by tony-iqlusion** [comment]
#275 automates the patching process, using the following names:

- `pub struct Validators` (same as original generated code)
- `pub enum Policy` (as suggested in https://github.com/cosmos/cosmos-sdk/issues/12316)

Still, it would be good to find a solution for this issue that doesn't involve patching generated code.

**Comment by tony-iqlusion** [comment]
Going to go ahead and close this as there is now an automated solution.

Fixing the name clash is tracked as https://github.com/cosmos/cosmos-sdk/issues/12316
