### ISSUE TITLE
Question: Should field `amount` be None in MsgUndelegate

### ISSUE THREAD

**Issue by stevenatcrypto** [cosmos/cosmos-rust#174]
Hi, I found the field `amount` in MsgUndelete is type of `Option<Coin>` (different in MsgDelegate). Could it be assigned to None? And why? Thanks.

https://github.com/cosmos/cosmos-rust/blob/main/cosmrs/src/staking.rs#L83

**Comment by tony-iqlusion** [comment]
It's [non-nullable in the schema](https://github.com/cosmos/cosmos-sdk/blob/9fd866e3820b3510010ae172b682d71594cd8c14/proto/cosmos/staking/v1beta1/tx.proto#L120) and should probably receive the same treatment as #124
