### ISSUE TITLE
`prost-wkt-build` to support `Any::{try_pack, try_unpack}` in `cosmos-sdk-proto`

### ISSUE THREAD

**Issue by rnbguy** [cosmos/cosmos-rust#176]
My [`cosmos-sdk-proto` fork](https://github.com/rnbguy/cosmos-rust) is using [`prost-wkt-build`](https://github.com/fdeantoni/prost-wkt) to support `Any::{try_pack, try_unpack}` via Serde (de)serialization.

`prost-wkt` still has [some issues](https://github.com/fdeantoni/prost-wkt#oneof-types). But I manually fixed them all.

If `prost-wkt` looks alright, I would be happy to create a PR with my fork.

**Comment by tony-iqlusion** [comment]
#185 also seems related to this

**Comment by rnbguy** [comment]
Ah. Makes sense. Feel free to close this issue for now. :slightly_smiling_face:

**Comment by tony-iqlusion** [comment]
Here's an upstream issue on tendermint-rs: https://github.com/informalsystems/tendermint-rs/issues/1053

I'd suggest any further discussion happens there. The crates in this repo will adopt whatever solution is used upstream.
