### ISSUE TITLE
Use Google's Protobuf well-known types definitions instead of `prost_types`

### ISSUE THREAD

**Issue by stevenatcrypto** [cosmos/cosmos-rust#185]
According to [this recent PR](https://github.com/informalsystems/ibc-rs/pull/2005) of `ibc-rs`, should we also use Google's Protobuf well-known types definitions instead of `prost_types` to derive `Serialize` and `Deserialize`? Thanks.

**Comment by tony-iqlusion** [comment]
Here's an upstream issue on tendermint-rs: https://github.com/informalsystems/tendermint-rs/issues/1053

I'd suggest any further discussion happens there. The crates in this repo will adopt whatever solution is used upstream.
