### ISSUE TITLE
RustCrypto policy?

### ISSUE THREAD

**Issue by nickray** [cosmos/cosmos-rust#233]
Running into compatibility issues using `cosmrs` together with the upcoming `k256` Taproot feature. Is there an official policy on how and when to keep up with the relatively frequent breaking changes in RustCrypto libraries? E.g., would combined PRs to tendermint-rs/cosmos-rust have a chance of being merged + released?

**Comment by tony-iqlusion** [comment]
The `k256` update to v0.11 is already merged into tendermint-rs:

https://github.com/informalsystems/tendermint-rs/pull/1129

We'll bump it in `cosmrs` after the next release. As soon as there's another v0.11 release of `k256` with the Taproot Schnorr feature, they'll be compatible.

**Comment by tony-iqlusion** [comment]
`k256` has been updated to v0.11 in #253
