### ISSUE TITLE
Osmosis Proto

### ISSUE THREAD

**Issue by Philipp-Sc** [cosmos/cosmos-rust#236]
Hello,

thank you so much for working on this awesome repository.

How much effort would it be to add Osmosis and Terra?
I tried running the build, but something fails. I was able to manually add some [Osmosis](https://github.com/osmosis-labs/osmosis/tree/main/proto/osmosis) related messages.

If it is easy to archive by adding it to the main.rs file maybe I do not need to implement it manually.

Thank you in advance.
Best regards,
Philipp

**Comment by tony-iqlusion** [comment]
There's some ongoing discussion about this here: https://github.com/informalsystems/tendermint-rs/issues/654#issuecomment-1119466744

I suggested having a single repo where all of the protobufs could be managed consistently. So yes, I think it'd be a good idea to reuse the same infrastructure we have already for crates like `tendermint-proto` and `cosmos-sdk-proto` to be able to generate crates for the protos for other networks.

**Comment by Philipp-Sc** [comment]
I think this makes a lot of sense. From a technical perspective, what exactly needs to be done to make the main.rs work for osmosis? Just adjust the paths or are blockchain specific customizations needed as well?

**Comment by Philipp-Sc** [comment]
I got the `cargo run` to finish without errors with added paths for osmosis.
- ```'../cosmos-sdk-proto/src/prost/osmosisd'```
What about the process for the `lib.rs` and `cargo.toml` do they need to be edited manually, or is there a script for that as well?

**Comment by Philipp-Sc** [comment]
thank you, I just separated the code from the `cosmos-sdk-proto` into `osmosis-proto`. I tested it with a few queries and it seems to work fine with the Osmosis gRPC endpoint I have.

How Osmosis is setup, the endpoint sometimes return `google.protobuf.Any` for that I will need to add some handcrafted code, so it can easily be casted into the type it acutally represents. 

I will fork the branch you created and try to do a pull request.

**Comment by Philipp-Sc** [comment]
@tony-iqlusion pull request is out https://github.com/cosmos/cosmos-rust/pull/239

Let me know if you like me to make any changes before you merge it.

**Comment by Philipp-Sc** [comment]
Update: 
See [added osmosis specific cosmrs customization](https://github.com/cosmos/cosmos-rust/pull/239/commits/56631b033f538bcca7c3ec5558c35779df10ae8d) 

I think this is a good way to do it. Let me know if you have any feedback.

Thanks and best regards,
Philipp

**Comment by Philipp-Sc** [comment]
On another note: `tx/msg.rs` it would be great if the `MsgProto` implementations get generated by a script if possible. There are many types missing.

**Comment by Philipp-Sc** [comment]
Closing this issue.

**Comment by tony-iqlusion** [comment]
The `MsgProto` trait is gone. I assume you're referring to the `TypeUrl` trait?

Yes, that sure would be nice. There's an upstream issue about it on `prost` here:

https://github.com/tokio-rs/prost/issues/299

**Comment by Philipp-Sc** [comment]
If there was a way to get a list of all the `type urls` we could write a script to write the matching implementations.
Might be something to look into in the future. For the time being I am okay, with adding the types I need manually.

**Comment by tony-iqlusion** [comment]
It will hopefully get fixed upstream in the next release. There's already a few PRs.

If it really ends up continuing to be an issue we can look at automating it.
