### ISSUE TITLE
Track `prost-types` release for `Duration` error propagation

### ISSUE THREAD

**Issue by neacsu** [cosmos/cosmos-rust#252]
The current `prost-types` dependency version doesn't support proper Duration error propagation, which should be fixed when https://github.com/tokio-rs/prost/pull/625 is included in a release.

Once that is done, we can also expose `PeriodicAllowance`, similarly to how we did in https://github.com/cosmos/cosmos-rust/pull/250 for `MsgGrantAllowance`, `MsgRevokeAllowance`, `BasicAllowance` and
`AllowedMsgAllowance`

**Comment by tony-iqlusion** [comment]
`prost` was updated to v0.11 in #277
