### ISSUE TITLE
feature request: general query support

### ISSUE THREAD

**Issue by scalalang2** [cosmos/cosmos-rust#262]
I hope it supports general query such as `GetBalance`, `GetUnclaimedReward` and more.

**Comment by scalalang2** [comment]
Can I use it with `tonic` ?

**Comment by tony-iqlusion** [comment]
If you enable the `grpc` features of `cosmrs` (it's enabled by-default for `cosmos-sdk-proto`) the gRPC clients will be available.

We don't presently provide wrappers for them (or plan on it, work like that is largely happening in Ocular): https://github.com/PeggyJV/ocular
