### ISSUE TITLE
Custom Configuration for Endpoints / Channels.

### ISSUE THREAD

**Issue by Philipp-Sc** [cosmos/cosmos-rust#290]
Currently there is no way to access `tonic::transport::channel::endpoint::Endpoint`.
For example one might want to use [tls_config()](https://docs.rs/tonic/latest/tonic/transport/channel/struct.Endpoint.html#method.tls_config) or other timeout related methods.

```
let mut endpoint = Endpoint::new("url".parse().unwrap()).unwrap();
endpoint = endpoint.tls_config();
// expected would be that something like the following works:
// MsgClient::connect(endpoint).await; 
// MsgClient::new(endpoint.connect().await?);
```

Relevant Code Example:
``` pub struct MsgClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    #[cfg(feature = "grpc-transport")]
    #[cfg_attr(docsrs, doc(cfg(feature = "grpc-transport")))]
    impl MsgClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: std::convert::TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
```
https://github.com/cosmos/cosmos-rust/blob/main/cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.gov.v1beta1.rs

Please let me know if I am missing something.

**Comment by Philipp-Sc** [comment]
A temporary fix would be to replace
`inner: tonic::client::Grpc<T>,`
with
`pub inner: tonic::client::Grpc<T>,`

maybe there is a better solution?

**Comment by tony-iqlusion** [comment]
This seems like more of a `tonic` usage question which I'm not completely sure I know the right answer to. You're talking about something in the generated code, and I don't think it makes sense to modify that in this instance.

You're saying `MsgClient::new(endpoint.connect().await?)` doesn't work? What's the specific problem?

**Comment by Philipp-Sc** [comment]
The reason I run into this, is because I have troubles connecting with an Osmosis gRPC endpoint. (Other endpoints for example Terra or Juno work fine.)

The error I get with Osmosis is:
`transport error, http2, invalid frame size` as well as sometimes a `connection reset`

I have two tests [here](https://github.com/Philipp-Sc/cosmos-rust-package/blob/main/src/api/custom/query/gov/mod.rs).

So far my guess is that I might be able to solve the above problem via [tls_config()](https://docs.rs/tonic/latest/tonic/transport/channel/struct.Endpoint.html#method.tls_config).

I put the following code for testing in:

```
let my_endpoint = MyEndpoint {
            endpoint: tonic::transport::Endpoint::new(grpc_url.parse().unwrap()).unwrap(), 
        };
QueryClient::new(my_endpoint.endpoint.connect().await?);
```
[See here](https://github.com/Philipp-Sc/cosmos-rust-package/blob/main/src/api/core/cosmos/channels/mod.rs)

this does not compile. Because QueryClient::new(..) has specific trait requirements:

```
error[E0277]: the trait bound `tonic::transport::Channel: tonic::codegen::Service<http::request::Request<http_body::combinators::box_body::UnsyncBoxBody<cosmos_sdk_proto::prost::bytes::Bytes, tonic::status::Status>>>` is not satisfied
  --> src/api/core/cosmos/channels/mod.rs:61:26
   |
61 |         QueryClient::new(my_endpoint.endpoint.connect().await?);
   |         ---------------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `tonic::codegen::Service<http::request::Request<http_body::combinators::box_body::UnsyncBoxBody<cosmos_sdk_proto::prost::bytes::Bytes, tonic::status::Status>>>` is not implemented for `tonic::transport::Channel`
   |         |
   |         required by a bound introduced by this call
   |
   = help: the trait `tonic::codegen::Service<http::request::Request<http_body::combinators::box_body::UnsyncBoxBody<cosmos_sdk_proto::prost::bytes::Bytes, Status>>>` is implemented for `tonic::transport::Channel`
   = note: required because of the requirements on the impl of `tonic::client::service::GrpcService<http_body::combinators::box_body::UnsyncBoxBody<cosmos_sdk_proto::prost::bytes::Bytes, tonic::status::Status>>` for `tonic::transport::Channel`

```

`QueryClient::connect()` does not accept an Entrypoint, it only accepts something that can be turned into one.  Therefore my dilemma.

**Comment by tony-iqlusion** [comment]
I'd suggest opening an upstream `tonic` issue

**Comment by Philipp-Sc** [comment]
Solved. My mistake, I was using an outdated tonic version.
