### ISSUE TITLE
Development Status

### ISSUE THREAD

**Issue by swisstackle** [cosmos/cosmos-rust#342]
How's it going.

Me and my buddy have to make a design decision for our module to use Rust or Go. We would like to use Rust for many reasons.

Two questions:

- Is this still being developed?
- If existing Go Cosmos Blockchains would like to use a module written in rust, how would they go about that? I am assuming it's not possible or only through special bindings. The reason why I am asking is because our modules would have to be usable by other people in their own Blockchains.

**Comment by tony-iqlusion** [comment]
This repo is actively developed, however be aware of the caveats that it's a primarily client-oriented library (which is also useful for CosmWasm).

If you want to write an ABCI app in Rust which uses the Go implementation of Tendermint, check out https://github.com/penumbra-zone/tower-abci
