### ISSUE TITLE
proto-build "No such file or directory"

### ISSUE THREAD

**Issue by Philipp-Sc** [cosmos/cosmos-rust#359]
It took me some time to figure out what was missing, since the rust error complains about a file/directory.

```rust
thread 'main' panicked at 'exit status missing: Os { code: 2, kind: NotFound, message: "No such file or directory" }', proto-build/src/main.rs:134:10
```

I am on linux so I installed buf via npm and updated main.rs to run "npx buf" instead of "buf".

```javascript
npm install @bufbuild/buf
```

```rust
 run_cmd(
        "npx",
        vec![
            "buf",
            "generate",
            "--template",
            "buf.wasmd.gen.yaml",
            "--include-imports",
            "-o",
            &out_dir.display().to_string(),
            &proto_path.display().to_string(),
        ],
    );
```

For  convenience it would be great to have a README.md that mentions the requirements.

Otherwise good work!

Best regards,
Philipp-Sc

**Comment by tony-iqlusion** [comment]
This was just merged a couple days ago, so it's a little rough around the edges: #358

**Comment by tony-iqlusion** [comment]
The ergonomics here should've been improved by #387
