### ISSUE TITLE
TallyParams Undocumented Decimal Type

### ISSUE THREAD

**Issue by Philipp-Sc** [cosmos/cosmos-rust#372]
Hi,

the documentation regarding the TallyParams is basically non existent, after a some trial and error I found out how the decimals are encoded:

https://github.com/cosmos/cosmos-rust/blob/main/cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.gov.v1beta1.rs
```rust
/// TallyParams defines the params for tallying votes on governance proposals.
///
/// ```
/// let dec_encoded: Vec<u8> = vec![53, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48]; 
/// let decimal_string = String::from_utf8_lossy(&dec_encoded).to_string();  
/// let decimal_int = decimal_string.parse::<u128>().unwrap(); 
/// let decimal = decimal_int as f64 / 10_u128.pow(18) as f64; // Divide the integer by 10^18 to obtain the decimal value
/// println!("decimal: {:?}",decimal);
/// ```
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TallyParams {
    ///   Minimum percentage of total stake needed to vote for a result to be
    ///   considered valid.
    #[prost(bytes = "vec", tag = "1")]
    pub quorum: ::prost::alloc::vec::Vec<u8>,
    ///   Minimum proportion of Yes votes for proposal to pass. Default value: 0.5.
    #[prost(bytes = "vec", tag = "2")]
    pub threshold: ::prost::alloc::vec::Vec<u8>,
    ///   Minimum value of Veto votes to Total votes ratio for proposal to be
    ///   vetoed. Default value: 1/3.
    #[prost(bytes = "vec", tag = "3")]
    pub veto_threshold: ::prost::alloc::vec::Vec<u8>,
}
```

I am not sure where the right place is to update/add to the documentation. This particularly might also soon be fixed with a later release, but it may make sense to collect and document cases like this.

**Comment by tony-iqlusion** [comment]
That code and documentation is auto-generated from the protos in https://github.com/cosmos/cosmos-sdk

You can add upstream documentation there but it needs to be language agnostic.

For improving the Rust experience, it would be good to define a wrapper type in `cosmrs` that implements the encoding, rather than just documenting it.

**Comment by Philipp-Sc** [comment]
closing this, wrote a [wrapper](https://github.com/Philipp-Sc/cosmos-rust-package/blob/main/src/api/custom/types/gov/params_ext.rs) to convert the type already a while ago.
