### ISSUE TITLE
Maybe Can Use only one crate `cosmos-sdk-proto` or `ibc-proto-rs`

### ISSUE THREAD

**Issue by DaviRain-Su** [cosmos/cosmos-rust#398]
this is ibc-proto-rs: https://github.com/cosmos/ibc-proto-rs/tree/main

**Comment by tony-iqlusion** [comment]
I have no idea what you're asking here

**Comment by DaviRain-Su** [comment]
And cosmos-sdk-proto use different cosmos-sdk, ibc-go version with ibc-proto. and also problem is cosmos-sdk-proto is not support `no-std`.

**Comment by tony-iqlusion** [comment]
It seems like you should file this issue against `ibc-proto-rs` instead of here? I'm not sure what we can do per se.

**Comment by DaviRain-Su** [comment]
I am wondering if it is possible to merge the files generated by `cosmos-sdk-proto` into `ibc-proto-rs`.

**Comment by tony-iqlusion** [comment]
Seems like you should open an issue at https://github.com/cosmos/ibc-proto-rs/issues then
