### ISSUE TITLE
wasm-bindgen issue when using cosmrs in CosmWasm

### ISSUE THREAD

**Issue by webmaster128** [cosmos/cosmos-rust#407]
In https://github.com/cosmos/cosmos-rust/blob/cosmrs/v0.14.0/cosmrs/Cargo.toml#L31-L32 there is a JS-only dependency added in case of a wasm32 compilatiion target. The "js" feature of getrandom makes it use wasm-bindgen to call into JS.

This makes the library unusable in all non-JS Wasm environments, such as CosmWasm. This is unfortunate also since this is hard to debug for users.

Can this be changed somehow? ~Is getrandom even used? At first glance I don't see a usage of it.~

**Comment by DaviRain-Su** [comment]
enen. cosmos rust need support no std.

Simon Warta ***@***.***>于2023年6月6日 周二15:10写道：

**Comment by tony-iqlusion** [comment]
I'm not a WASM expert and open to alternatives here. What would you suggest?

**Comment by tony-iqlusion** [comment]
> Can this be changed somehow? Is getrandom even used? At first glance I don't see a usage of it.

I would suggest making an attempt to remove `getrandom`. It's not as easy as it first appears.

**Comment by webmaster128** [comment]
> I'm not a WASM expert and open to alternatives here. What would you suggest?

The issue in the dependency is that JavaScript dependency and Wasm is mixed. Having a `js` feature in cosmrs could be a solution.

However, high level I don't know what cosmrs does and to what degree it needs randomness.

**Comment by tony-iqlusion** [comment]
It's needed to support key generation. I guess that could potentially be gated under a feature.

**Comment by DaviRain-Su** [comment]
> @DaviRain-Su WASM isn't a `no_std` environment. That's a separate issue.

I know but wasm32-unknown-unknown is part of no_std environment.

**Comment by tony-iqlusion** [comment]
libstd is available on wasm32-unknown-unknown

**Comment by DaviRain-Su** [comment]
> libstd is available on wasm32-unknown-unknown

I know but pallet-* in substrate use wasm32-unknown-unknown as compiler targeting. And also the pallet-* support no_std.

**Comment by tony-iqlusion** [comment]
`no_std` crates work on any platform, but that's unrelated to WASM
