### ISSUE TITLE
Type URLs for x/authz messages not present

### ISSUE THREAD

**Issue by AmitPr** [cosmos/cosmos-rust#408]
In `cosmos-sdk-proto`, I'm not seeing any Type URL implementations for any of the messages in the `x/authz` module. For example, `MsgGrant`, or `GenericAuthorization`.

**Comment by DaviRain-Su** [comment]
https://github.com/cosmos/cosmos-rust/blob/main/cosmos-sdk-proto/src/type_urls.rs This file maybe have not impl for the type.

**Comment by tony-iqlusion** [comment]
Yeah, right now adding the type URLs is a manual process unfortunately.

I opened an upstream PR which attempts to upstream some of the work from these crates so it can be automated with prost-build: https://github.com/tokio-rs/prost/pull/858

**Comment by AmitPr** [comment]
Gotcha. Yeah it's not a super big deal even now as I can manually input the Type URLs when serializing to `any`. Just would be nice to have this all consistent!

**Comment by tony-iqlusion** [comment]
As a stopgap we could possibly add something to `proto-build`

**Comment by tony-iqlusion** [comment]
We now autogenerate `prost::Name` annotations using `buf` for all types
