### ISSUE TITLE
gov/v1

### ISSUE THREAD

**Issue by Philipp-Sc** [cosmos/cosmos-rust#420]
Hi,

is there a reason **gov/v1** is not available as export?
 
 ```rust
/// Messages and services handling governance
    pub mod gov {
        pub mod v1beta1 {
            include!("prost/cosmos-sdk/cosmos.gov.v1beta1.rs");
        }
    }
```

I want to use the newer **gov/v1** instead of **gov/v1beta**, since I get the following error quite often when querying for proposals.

```codespace sdk code 29: invalid type: can't convert a gov/v1 Proposal to gov/v1beta1 Proposal when amount of proposal messages is more than one```

**Comment by tony-iqlusion** [comment]
Added in #437
