### ISSUE TITLE
Does this crate only supports gRPC for querying contracts states?

### ISSUE THREAD

**Issue by felipepimsil** [cosmos/cosmos-rust#422]
I was trying to querying some data like cosmjs with a rpc, but it seems that cosmrs only supports gRPC.

**Comment by tony-iqlusion** [comment]
There actually isn't any native gRPC support, and little RPC support in general, in CosmRS.

For Tendermint RPC (i.e. HTTP+JSON `[rpc]`), see https://docs.rs/tendermint-rpc/

Note: gRPC support is currently in Ocular: https://github.com/PeggyJV/ocular

**Comment by felipepimsil** [comment]
@tony-iqlusion But how can I query some contract state?

In cosmjs lib, I can do:
```
  const queryClient = await CosmWasmClient.connect(RPC_URL);
   const queryMessage = {
    pairs: {
      limit: 10,
    },
  };

  const queryResult = await queryClient.queryContractSmart(
    '<MY_ADDRESS>',
    queryMessage
  );

```

I can't find a way to do it with a rust crate. I'm a little bit confused, as I can't find some examples.
I'm more used to EVM networks and still learning how to interact with cosmos blockchains like SEI, JUNO, etc.

**Comment by tony-iqlusion** [comment]
I'm not sure of a solution. If you'd like to contribute the relevant RPCs to CosmRS, we'd accept them.

**Comment by felipepimsil** [comment]
@tony-iqlusion I find a way to do this.
Maybe I'ill open a PR with some examples of queries/msgs.
