### ISSUE TITLE
Update crypto lib

### ISSUE THREAD

**Issue by Morgandri1** [cosmos/cosmos-rust#425]
Hello!
I did a brief look-over of the crate and noticed that it implements ``secp256k1`` and was having some issues with the signing key. 

This may be due to me not researching fully, but how can I derive my signing key from my private key? using a mnemonic w/ derivation path is a pain, and not great for some applications where a privateKey is simpler. 

I propose an update which supports the use of secret keys and signing TXs with the private key

**Comment by tony-iqlusion** [comment]
"Signing key" is just the nomenclature this library uses for a private key.

You can find a full signing example here: https://docs.rs/cosmrs/latest/cosmrs/tx/index.html#usage

You can use [`SigningKey::from_slice`](https://docs.rs/cosmrs/latest/cosmrs/crypto/secp256k1/struct.SigningKey.html#method.from_slice) if you have an existing private key serialized as bytes.

**Comment by Morgandri1** [comment]
Thank you for that info. 
I would suggest possibly adding that to docs or adding a from_string helper, something like that.
