### ISSUE TITLE
405 Method Not Allowed

### ISSUE THREAD

**Issue by penso** [cosmos/cosmos-rust#427]
I'm trying to build manually the protobuf files with: `buf generate --template buf.sdk.gen.yaml --include-imports -o /tmp/tmp-protobuf/cosmos-sdk ../cosmos-sdk-go/proto` but keep getting `Failure: 405 Method Not Allowed`.

`buf.sdk.gen.yaml` is pointing to `buf.build/prost/plugins/prost:v0.2.1-1` but https://buf.build/prost/ is empty. Has anything been removed since?

Thanks.

**Comment by tony-iqlusion** [comment]
I assume this means that the `buf`/`prost` integration has changed yet again. Sigh.

**Comment by tony-iqlusion** [comment]
I opened #429 to attempt to address this but the plugin at the new location is no longer working
