### ISSUE TITLE
Update ibc-go types

### ISSUE THREAD

**Issue by srdtrk** [cosmos/cosmos-rust#442]
ibc-go types are outdated. For example, none of the packet data memo fields are included

**Comment by tony-iqlusion** [comment]
Yeah, #423 is open with some updates.

I held off on doing those in the `cosmos-sdk-proto` v0.20 release because of all of the other changes and so we had at least one release with Tendermint v0.34 support that included a prost v0.12 upgrade.

That said, I can take a look at trying to rebase #423.

**Comment by tony-iqlusion** [comment]
As of #492 we're now updated to the latest version: v8.4.0
