### ISSUE TITLE
 proto-build: bump COSMOS_SDK_REV to v0.47 or higher

### ISSUE THREAD

**Issue by Philipp-Sc** [cosmos/cosmos-rust#450]
**Can not find MsgCommunityPoolSpend**

Type URL:
```/cosmos.distribution.v1beta1.MsgCommunityPoolSpend```

https://github.com/cosmos/cosmos-sdk/blob/main/proto/cosmos/protocolpool/v1/tx.proto

**Comment by Philipp-Sc** [comment]
Found it provided here:
https://docs.rs/injective-std/latest/injective_std/types/cosmos/distribution/v1beta1/index.html

**Comment by Philipp-Sc** [comment]
Since: cosmos-sdk 0.47

**Comment by tony-iqlusion** [comment]
See #423

**Comment by tony-iqlusion** [comment]
We're now on v0.50.9 as of #488
