### ISSUE TITLE
Querying `minimum_gas_price` 

### ISSUE THREAD

**Issue by daniel-savu** [cosmos/cosmos-rust#455]
Hi, I'm trying to query the `minimum_gas_price` configured by the node, as added in https://github.com/cosmos/cosmos-sdk/pull/13485 at `/cosmos/base/node/v1beta1/config`. 

I noticed the protobuf methods are already in place here: https://github.com/cosmos/cosmos-rust/blob/main/cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.base.node.v1beta1.tonic.rs

However it doesn't look like this is exposed in `cosmos-sdk-proto`. Is this rpc call currently supported in `cosmrs`?

**Comment by tony-iqlusion** [comment]
Doesn't look like that one is wired up yet. The re-exports happen here: https://github.com/cosmos/cosmos-rust/blob/main/cosmos-sdk-proto/src/lib.rs

**Comment by tony-iqlusion** [comment]
Doesn't look like that one is wired up yet. The re-exports happen here: https://github.com/cosmos/cosmos-rust/blob/main/cosmos-sdk-proto/src/lib.rs

**Comment by daniel-savu** [comment]
Are there any plans to export this in the near future? Happy to open a PR myself if needed

**Comment by tony-iqlusion** [comment]
Please do!

**Comment by tony-iqlusion** [comment]
It should be available here now:

https://docs.rs/cosmos-sdk-proto/0.24.0/cosmos_sdk_proto/cosmos/base/node/v1beta1/service_client/struct.ServiceClient.html#method.config

https://docs.rs/cosmos-sdk-proto/0.24.0/cosmos_sdk_proto/cosmos/base/node/v1beta1/struct.ConfigResponse.html#structfield.minimum_gas_price
