### ISSUE TITLE
How to output the private key and print it to the terminal？

### ISSUE THREAD

**Issue by RustMan88** [cosmos/cosmos-rust#456]
The fmt trait is not implemented for crypto::secp256k1::SigningKey , So how to output the private key and print it to the terminal？

**Comment by micovi** [comment]
Hi @RustMan88, did you manage to find a way to output private keys in the terminal using this?

**Comment by tony-iqlusion** [comment]
`crypto::secp256k1::SigningKey` can't be output to the terminal.

It's a wrapper type for a trait object, and designed to support hardware key storage as well including e.g. hardware wallets / HSMs, in addition to software-backed keys.

If you want the original key, you need to use your original input you instantiated it with.
