### ISSUE TITLE
ibc-go ::prost::Name implementations gone in cosmos-sdk-proto v0.24.0

### ISSUE THREAD

**Issue by Buckram123** [cosmos/cosmos-rust#497]
#491 PR removes `::prost::Name` implementations for ibc-go types. I assume that was an accident as I don't see it's noticed in changelog.

**Comment by tarcieri** [comment]
FWIW, the IBC protos are going to be removed in the next release and made available via the `ibc-proto` crate instead. See #495

**Comment by Buckram123** [comment]
Ok, it solves it, thanks!
