### ISSUE TITLE
status of subdirectories in project READMEs

### ISSUE THREAD

**Issue by hxrts** [cosmos/cosmos-rust#69]
I've had a few people ask me about the rust transaction builder and I've pointed them to this repo, however if the readme for that project said a little more about what's currently supported/unsupported and maturity I think that may help newbies.

**Comment by marbar3778** [comment]
We should also add docs on how to use this repo, some examples would go a long way. 

When we get some short examples we can work on rendering it on the docs.cosmos.network site.

**Comment by tony-iqlusion** [comment]
I'll add usage docs after I have an end-to-end test written and know it actually works 😉
