### ISSUE TITLE
adding support for json

### ISSUE THREAD

**Issue by leejw51crypto** [cosmos/cosmos-rust#83]
messages in the tx are encoded with protobuf,
need to know class first to decode by `typeurl`

if those messages can be parsed into serde_json, it would be easy to display
how about adding serde json support in compiling rust files from proto files?
(in prost)

**Comment by tony-iqlusion** [comment]
We'd definitely like to add JSON support. Some complicating factors are a planned transition to "Proto JSON" from the previous "Amino JSON" was put on hiatus, or at least that's my understanding, but it may be out-of-date.

It'd be good to examine current and future strategies for JSON support in tendermint-rs so we can align with what they're doing, and ideally reuse some of their work:

https://github.com/informalsystems/tendermint-rs/issues/654

**Comment by devashishdxt** [comment]
@tony-iqlusion We can use [`pbjson`](https://docs.rs/pbjson-build/latest/pbjson_build/) for this?

**Comment by tony-iqlusion** [comment]
@devashishdxt unfortunately it seems like the JSON that's required (e.g. by `ibc-rs`/Hermes) differs from the standard Protobuf JSON, or at least that's my understanding.

See ample discussion on https://github.com/informalsystems/tendermint-rs/issues/654

**Comment by scalalang2** [comment]
What if we add struct attributes ?
See this link : https://github.com/tokio-rs/prost/issues/75#issuecomment-365371756

**Comment by tony-iqlusion** [comment]
If there's consensus that Cosmos SDK will eventually migrate to [Protobuf JSON](https://developers.google.com/protocol-buffers/docs/proto3#json), then I'm fine with using something like `pbjson` like @devashishdxt recommended.

**Comment by hxrts** [comment]
relevant cosmwasm discussion https://github.com/CosmWasm/cosmwasm/issues/1448

**Comment by ewoolsey** [comment]
Any updates on this? I'm trying to build a cosmos-ledger library and running into a wall. I need to be ale to convert an Any into JSON to display on the ledger, and can't figure out how to move forwards.

**Comment by ewoolsey** [comment]
As a side note, is there currently any workaround I can use to get this functionality? I've been trying for an hour or two and I can't seem to come up with a way to get json from an Any, or any of the other message types for that matter.

**Comment by tony-iqlusion** [comment]
`Any` contains a serialized proto, so you won't ever be able to just "convert it into JSON".

Instead you'll first need to convert it to the appropriate concrete type for a `type_url`, and then once you have an actual protobuf type, that type can potentially be serialized by `pbjson`.

Again, that's something we can potentially support, although AFAIK everything else is currently using the legacy Amino JSON so it won't provide interop. But it would work for your kind of use case, or if someone wanted to build a JSON RPC API.

**Comment by ewoolsey** [comment]
Yes sorry I wasn't completely clear, I don't need to convert to json for Any, but rather for all of types that are Msg. Even just ```#[derive(Serialize)]``` would work for my use case. Would it be useful to submit a PR with Serialize, Deserialize, derived on all of the Msg types in cosmrs? Could put it behind a feature gate as well.

**Comment by tony-iqlusion** [comment]
No, we don't want to add a bespoke JSON format. It really needs to be `pbjson` or Amino JSON, and I would generally prefer not to support the latter except as a last resort if a Protobuf JSON migration upstream falls through as it will require a lot of manual work

**Comment by ewoolsey** [comment]
Gotcha, so am I stuck with re-deriving all the Msg structs myself? Or do you see another way for me to achieve that?

**Comment by tarcieri** [comment]
A PR adding `pbjson` support seems reasonable to me

**Comment by ewoolsey** [comment]
I have no experience with that library and I'm not really sure what that would entail. Which types in particular should pbjson be applied to?

**Comment by tony-iqlusion** [comment]
It automatically builds `serde`-serializable structs for all types in the Protobuf schema, whose structure conforms to the [Protobuf JSON Mapping](https://developers.google.com/protocol-buffers/docs/proto3#json)

https://docs.rs/pbjson-build/latest/pbjson_build/

**Comment by tony-iqlusion** [comment]
Fixed in #471
