### ISSUE TITLE
Remaining Placeholder In LICENSE

### ISSUE THREAD

**Issue by loloicci** [cosmos/cosmos-rust#94]
https://github.com/cosmos/cosmos-rust/blob/d674c6e26e8cdd628be165609a25b3cc5c8bc20c/LICENSE#L189

This should be rewrited.

**Comment by tony-iqlusion** [comment]
This is part of the standard boilerplate of the Apache 2.0 license describing how to apply the license, namely what comments should be present at the top of source code files.

Granted we aren't following their prescribed procedure, and perhaps should, but that is not specifically a part of the `LICENSE` file itself which is supposed to be modified on a per-project basis.
